# Generated by Django 6.0.4 on 2026-04-20 10:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('webhook', 'Webhook')], default='telegram', max_length=30)),
                ('delivery_type', models.CharField(choices=[('instant', 'Instant'), ('digest', 'Digest')], default='instant', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('recipient', models.CharField(blank=True, help_text='Target recipient, for example Telegram chat id, email or webhook alias.', max_length=255)),
                ('idempotency_key', models.CharField(editable=False, help_text='Deterministic key used to prevent duplicate alert deliveries.', max_length=500, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Notification payload prepared for delivery.')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Provider response payload after delivery attempt.')),
                ('provider_message_id', models.CharField(blank=True, help_text='External provider message id after successful delivery.', max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
