# Generated by Django 6.0.4 on 2026-04-19 19:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_event_detection_source_event_ignored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('webhook', 'Webhook')], default='telegram', max_length=30)),
                ('delivery_type', models.CharField(choices=[('instant', 'Instant'), ('digest', 'Digest')], default='instant', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=30)),
                ('recipient', models.CharField(blank=True, help_text='Target recipient, for example Telegram chat id, email or webhook alias.', max_length=255)),
                ('idempotency_key', models.CharField(editable=False, help_text='Deterministic key used to prevent duplicate alert deliveries.', max_length=500, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Notification payload prepared for delivery.')),
                ('response_payload', models.JSONField(blank=True, default=dict, help_text='Provider response payload after delivery attempt.')),
                ('provider_message_id', models.CharField(blank=True, help_text='External provider message id after successful delivery.', max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='monitoring.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='monitoring.monitoringprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='alerts_aler_profile_9381fc_idx'), models.Index(fields=['event', 'status'], name='alerts_aler_event_i_f71372_idx'), models.Index(fields=['channel', 'status'], name='alerts_aler_channel_68c974_idx'), models.Index(fields=['delivery_type'], name='alerts_aler_deliver_5a18be_idx'), models.Index(fields=['scheduled_at'], name='alerts_aler_schedul_959846_idx'), models.Index(fields=['next_retry_at'], name='alerts_aler_next_re_462f9c_idx'), models.Index(fields=['idempotency_key'], name='alerts_aler_idempot_053ca8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='alert_delivery_max_attempts_gte_1')],
            },
        ),
    ]
