# Generated by Django 6.0.4 on 2026-04-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='monitoring.event'),
        ),
        migrations.AddField(
            model_name='alertdelivery',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to='monitoring.monitoringprofile'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['profile', 'status'], name='alerts_aler_profile_9381fc_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['event', 'status'], name='alerts_aler_event_i_f71372_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['channel', 'status'], name='alerts_aler_channel_68c974_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['delivery_type'], name='alerts_aler_deliver_5a18be_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['scheduled_at'], name='alerts_aler_schedul_959846_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['next_retry_at'], name='alerts_aler_next_re_462f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['idempotency_key'], name='alerts_aler_idempot_053ca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='alert_delivery_max_attempts_gte_1'),
        ),
    ]
