# Generated by Django 6.0.4 on 2026-04-20 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('telegram_account', 'Telegram account'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook'), ('other', 'Other')], default='telegram_bot', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('disabled', 'Disabled'), ('error', 'Error')], default='pending', max_length=20)),
                ('name', models.CharField(help_text='User-friendly source name, for example Telegram sales bot.', max_length=120)),
                ('external_id', models.CharField(blank=True, help_text='External source id, for example bot id, account id or webhook id.', max_length=255)),
                ('external_username', models.CharField(blank=True, help_text='External username, for example Telegram bot username.', max_length=255)),
                ('credentials_encrypted', models.TextField(blank=True, help_text='Encrypted credentials. Never display this value in admin.')),
                ('credentials_fingerprint', models.CharField(blank=True, help_text='Short non-sensitive fingerprint for identifying configured credentials.', max_length=16)),
                ('webhook_secret', models.CharField(blank=True, help_text='Optional secret for validating incoming webhook requests.', max_length=255)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
