# Generated by Django 6.0.4 on 2026-04-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedsource',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_sources', to='monitoring.monitoringprofile'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['owner', 'status'], name='integration_owner_i_dede28_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['profile', 'status'], name='integration_profile_e7f8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['source_type'], name='integration_source__6212fb_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['external_id'], name='integration_externa_b88c73_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['is_deleted'], name='integration_is_dele_071a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('external_id', ''), _negated=True)), fields=('profile', 'source_type', 'external_id'), name='unique_active_source_per_profile_type_external_id'),
        ),
    ]
