# Generated by Django 6.0.4 on 2026-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedsource',
            name='webhook_secret_token',
            field=models.CharField(blank=True, help_text='Telegram webhook secret token used in X-Telegram-Bot-Api-Secret-Token header.', max_length=255),
        ),
    ]
