# Generated by Django 6.0.4 on 2026-04-25 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_connectedsource_webhook_secret_token'),
        ('monitoring', '0009_rename_monitoring__digest_bf2c2f_idx_monitoring__digest__8956e9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedsource',
            name='previous_webhook_secret',
            field=models.CharField(blank=True, db_index=True, help_text='Previous webhook path secret accepted during rotation grace period.', max_length=255),
        ),
        migrations.AddField(
            model_name='connectedsource',
            name='previous_webhook_secret_token',
            field=models.CharField(blank=True, help_text='Previous Telegram webhook secret token accepted during rotation grace period.', max_length=255),
        ),
        migrations.AddField(
            model_name='connectedsource',
            name='previous_webhook_secret_valid_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Until when previous webhook credentials are accepted.', null=True),
        ),
        migrations.AddField(
            model_name='connectedsource',
            name='webhook_secret_rotated_at',
            field=models.DateTimeField(blank=True, help_text='Last webhook secret rotation timestamp.', null=True),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['webhook_secret'], name='integration_webhook_834f98_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['previous_webhook_secret'], name='integration_previou_d4379c_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedsource',
            index=models.Index(fields=['previous_webhook_secret_valid_until'], name='integration_previou_19fac0_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('source_type', 'telegram_bot'), models.Q(('webhook_secret', ''), _negated=True)), fields=('webhook_secret',), name='unique_active_telegram_webhook_secret'),
        ),
        migrations.AddConstraint(
            model_name='connectedsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('source_type', 'telegram_bot'), models.Q(('previous_webhook_secret', ''), _negated=True)), fields=('previous_webhook_secret',), name='unique_active_previous_telegram_webhook_secret'),
        ),
    ]
