# Generated by Django 6.0.4 on 2026-05-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_connectedsource_previous_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedsource',
            name='source_type',
            field=models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('telegram_account', 'Telegram account'), ('gmail', 'Gmail'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhook'), ('other', 'Other')], default='telegram_bot', max_length=40),
        ),
    ]
