# Generated by Django 6.0.4 on 2026-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_connectedsource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedsource',
            name='source_type',
            field=models.CharField(choices=[('telegram_bot', 'Telegram bot'), ('telegram_account', 'Telegram account'), ('gmail', 'Gmail'), ('whatsapp_gateway', 'WhatsApp gateway'), ('whatsapp', 'WhatsApp Cloud API'), ('webhook', 'Webhook'), ('other', 'Other')], default='telegram_bot', max_length=40),
        ),
    ]
