# Generated by Django 6.0.4 on 2026-04-19 19:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scenario', models.CharField(choices=[('leads', 'Lead detection'), ('complaints', 'Complaint / negative feedback'), ('booking', 'Booking / request'), ('urgent', 'Urgent messages'), ('general', 'General monitoring'), ('custom', 'Custom')], default='general', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('business_context', models.TextField(blank=True, help_text='Optional plain text business context, max 300 characters.', validators=[django.core.validators.MaxLengthValidator(300)])),
                ('track_leads', models.BooleanField(default=True)),
                ('track_complaints', models.BooleanField(default=True)),
                ('track_requests', models.BooleanField(default=True)),
                ('track_urgent', models.BooleanField(default=True)),
                ('track_general_activity', models.BooleanField(default=False)),
                ('ignore_greetings', models.BooleanField(default=True)),
                ('ignore_short_replies', models.BooleanField(default=True)),
                ('ignore_emojis', models.BooleanField(default=True)),
                ('urgent_negative', models.BooleanField(default=True)),
                ('urgent_deadlines', models.BooleanField(default=True)),
                ('urgent_repeated_messages', models.BooleanField(default=True)),
                ('extract_name', models.BooleanField(default=True)),
                ('extract_contact', models.BooleanField(default=True)),
                ('extract_budget', models.BooleanField(default=True)),
                ('extract_product_or_service', models.BooleanField(default=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='telegram', max_length=30)),
                ('external_source_id', models.CharField(blank=True, help_text='External source identifier, for example Telegram bot or chat source.', max_length=255)),
                ('external_chat_id', models.CharField(blank=True, max_length=255)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(blank=True, max_length=255)),
                ('sender_username', models.CharField(blank=True, max_length=255)),
                ('sender_display_name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(editable=False, help_text='Deterministic key used to prevent duplicate message processing.', max_length=500, unique=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='monitoring.monitoringprofile')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('lead', 'Lead'), ('complaint', 'Complaint'), ('request', 'Request'), ('info', 'Info'), ('spam', 'Spam')], default='info', max_length=30)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('ignore', 'Ignore')], default='ignore', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('ignored', 'Ignored'), ('escalated', 'Escalated')], default='new', max_length=30)),
                ('priority_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('message_text_snapshot', models.TextField(blank=True, help_text='Message text copied from IncomingMessage for event history stability.')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Extracted fields like name, contact, budget, product_or_service.')),
                ('rule_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata from rule-based processing.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='monitoring.incomingmessage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.monitoringprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringprofile',
            index=models.Index(fields=['owner', 'status'], name='monitoring__owner_i_af2480_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprofile',
            index=models.Index(fields=['scenario'], name='monitoring__scenari_4e39db_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringprofile',
            index=models.Index(fields=['last_event_at'], name='monitoring__last_ev_79904d_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmessage',
            index=models.Index(fields=['profile', 'processing_status'], name='monitoring__profile_cf7798_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmessage',
            index=models.Index(fields=['channel', 'external_chat_id'], name='monitoring__channel_c3243c_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmessage',
            index=models.Index(fields=['received_at'], name='monitoring__receive_1954a9_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingmessage',
            index=models.Index(fields=['dedup_key'], name='monitoring__dedup_k_588cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['profile', 'status'], name='monitoring__profile_8852c5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['profile', 'priority'], name='monitoring__profile_935af0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='monitoring__categor_fe3364_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['priority_score'], name='monitoring__priorit_b89ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='monitoring__created_fff120_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('priority_score__gte', 0), ('priority_score__lte', 100)), name='event_priority_score_0_100'),
        ),
    ]
