# Generated by Django 6.0.4 on 2026-04-20 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], default='telegram', max_length=30)),
                ('external_source_id', models.CharField(blank=True, max_length=255)),
                ('external_chat_id', models.CharField(blank=True, max_length=255)),
                ('external_user_id', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('dedup_key', models.CharField(editable=False, help_text='Deterministic key used to identify the same external contact.', max_length=500, unique=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_contacts', to='monitoring.monitoringprofile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_contacts', to='integrations.connectedsource')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='external_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_messages', to='monitoring.externalcontact'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['profile', 'channel'], name='monitoring__profile_b79639_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['source'], name='monitoring__source__bb9d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['external_user_id'], name='monitoring__externa_14e1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['external_chat_id'], name='monitoring__externa_23ab24_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['username'], name='monitoring__usernam_3136cd_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['dedup_key'], name='monitoring__dedup_k_db7e09_idx'),
        ),
        migrations.AddIndex(
            model_name='externalcontact',
            index=models.Index(fields=['last_seen_at'], name='monitoring__last_se_5e3594_idx'),
        ),
    ]
