# Generated by Django 6.0.4 on 2026-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_externalcontact_incomingmessage_external_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('ignored', 'Ignored'), ('escalated', 'Escalated'), ('archived', 'Archived')], default='new', max_length=30),
        ),
    ]
