# Generated by Django 6.0.4 on 2026-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_event_archived_at_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='ai_daily_call_limit',
            field=models.PositiveIntegerField(default=30, help_text='Maximum AI analysis calls per day for this profile.'),
        ),
    ]
