# Generated by Django 6.0.4 on 2026-04-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoringprofile_ai_daily_call_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringprofile',
            name='ai_daily_call_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Leave empty to use the global AI_DAILY_CALL_LIMIT_PER_PROFILE setting.', null=True),
        ),
    ]
