# Generated by Django 6.0.4 on 2026-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_monitoringprofile_ai_daily_call_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringprofile',
            name='extract_date_or_time',
            field=models.BooleanField(default=True),
        ),
    ]
