# Generated by Django 6.0.4 on 2026-04-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_monitoringprofile_extract_date_or_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringprofile",
            name="digest_interval_hours",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Every hour"),
                    (3, "Every 3 hours"),
                    (6, "Every 6 hours"),
                    (12, "Every 12 hours"),
                    (24, "Every 24 hours"),
                ],
                default=1,
                help_text="How often digest notifications should be sent.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringprofile",
            index=models.Index(
                fields=["digest_interval_hours"],
                name="monitoring__digest_bf2c2f_idx",
            ),
        ),
    ]
