# Generated by Django 6.0.4 on 2026-04-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_monitoringprofile_digest_enabled'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitoringprofile',
            new_name='monitoring__digest__8956e9_idx',
            old_name='monitoring__digest_bf2c2f_idx',
        ),
        migrations.AlterField(
            model_name='monitoringprofile',
            name='ai_daily_call_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Leave empty to use the account-level AI daily call limit.', null=True),
        ),
        migrations.AlterField(
            model_name='monitoringprofile',
            name='digest_enabled',
            field=models.BooleanField(default=False, help_text='Enable grouped digest notifications for this profile.'),
        ),
    ]
