# Generated by Django 6.0.4 on 2026-04-19 19:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('fallback', 'Fallback')], default='pending', max_length=20)),
                ('model_provider', models.CharField(blank=True, help_text='AI provider name, for example OpenAI.', max_length=80)),
                ('model_name', models.CharField(blank=True, help_text='Model name, for example gpt-4o-mini.', max_length=120)),
                ('prompt_version', models.CharField(blank=True, help_text='Prompt version used for this analysis.', max_length=50)),
                ('input_text_snapshot', models.TextField(blank=True, help_text='Message text snapshot used for AI analysis.')),
                ('business_context_snapshot', models.TextField(blank=True, help_text='Business context snapshot used for AI analysis.')),
                ('category', models.CharField(blank=True, choices=[('lead', 'Lead'), ('complaint', 'Complaint'), ('request', 'Request'), ('info', 'Info'), ('spam', 'Spam')], max_length=30)),
                ('priority_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Extracted fields returned by AI.')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw parsed AI response.')),
                ('error_message', models.TextField(blank=True)),
                ('fallback_reason', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated AI request cost.', max_digits=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_latest', models.BooleanField(default=True, help_text='Marks the latest analysis result for this incoming message.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_result', to='monitoring.event')),
                ('incoming_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='monitoring.incomingmessage')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='monitoring.monitoringprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='ai_aianalys_profile_72d95e_idx'), models.Index(fields=['incoming_message', 'status'], name='ai_aianalys_incomin_653c56_idx'), models.Index(fields=['event'], name='ai_aianalys_event_i_416cb1_idx'), models.Index(fields=['model_name'], name='ai_aianalys_model_n_095954_idx'), models.Index(fields=['is_latest'], name='ai_aianalys_is_late_c4fcdf_idx'), models.Index(fields=['created_at'], name='ai_aianalys_created_770fc2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('priority_score__gte', 0), ('priority_score__lte', 100)), name='ai_analysis_priority_score_0_100'), models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('incoming_message',), name='unique_latest_ai_analysis_per_message')],
            },
        ),
    ]
