# Generated by Django 6.0.4 on 2026-04-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysisresult',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_result', to='monitoring.event'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='incoming_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='monitoring.incomingmessage'),
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='monitoring.monitoringprofile'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['profile', 'status'], name='ai_aianalys_profile_72d95e_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['incoming_message', 'status'], name='ai_aianalys_incomin_653c56_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['event'], name='ai_aianalys_event_i_416cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['model_name'], name='ai_aianalys_model_n_095954_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['is_latest'], name='ai_aianalys_is_late_c4fcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysisresult',
            index=models.Index(fields=['created_at'], name='ai_aianalys_created_770fc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='aianalysisresult',
            constraint=models.CheckConstraint(condition=models.Q(('priority_score__gte', 0), ('priority_score__lte', 100)), name='ai_analysis_priority_score_0_100'),
        ),
        migrations.AddConstraint(
            model_name='aianalysisresult',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('incoming_message',), name='unique_latest_ai_analysis_per_message'),
        ),
    ]
